### ISSUE TITLE
Struktura bazy danych

### ISSUE THREAD

**Issue by 6PJ9** [6PJ9/guest-book#8]
Księga gości musi gdzieś zapisywać wpisy. Użyjmy do tego celu bazy danych MySQL. Musisz zastanowić się jakie dane będą przechowywane i zaprojektować strukturę bazy (tabele). Na początku dla ułatwienia będzie tylko podstawowa funkcjonalność, czyli dodawanie wpisów do księgi. Każdy wpis zawiera treść, podpis gościa i ewentualnie jego adres email. Podpis i treść są obowiązkowe a email można podać dobrowolnie. Do stworzenia struktury w bazie możesz użyć np. PhpMyAdmin. Po stworzeniu struktury wklej mi wygenerowany kod SQL w komentarzu (użyj markdowna czyli wstaw w ` ``` `) i daj na `Code review`.

**Comment by fusen245** [comment]
CREATE TABLE `guest_book`.`entries` ( `id` INT UNSIGNED NOT NULL AUTO_INCREMENT , `entry` TEXT NOT NULL , `author` VARCHAR(50) NOT NULL , `email` VARCHAR(254) NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;
